version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: course-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: DigitalOcean2026Debesis
      MONGO_INITDB_DATABASE: course
    volumes:
      - mongo_data:/data/db

  course-domain:
    build: .
    image: course-domain:latest
    container_name: course-domain
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:DigitalOcean2026Debesis@mongodb:27017/course?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: course
    depends_on:
      - mongodb

volumes:
  mongo_data:                 # named volume — survives container restarts