spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.csziehqepxetdwdngujp
    password: 3c6Leg/xLAXnn5L
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: false
      file: course-domain/docker-compose.yml

  jpa:
    hibernate:
      ddl-auto: update