spring.application.name=course-domain
spring.mongodb.uri=mongodb://admin:DigitalOcean2026Debesis@165.245.223.137/course?authSource=admin&directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.8.2
spring.mongodb.database=course
